import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header.js";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar.js";
import Banner from "../components/Banner.js";
import Banner_2 from "../components/Banner_2.js";
import Testimonials from "../components/Testimonials.js";
import Banner_3 from "../components/Banner_3.js";
import Footer from "../components/Footer.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Faiz Bahu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Banner_2 />
      <Testimonials />
      <Banner_3 />
      <Footer />
    </>
  );
}
